# Generated by Django 5.1.4 on 2026-08-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PtaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('quote_type', models.CharField(choices=[('VENDA', 'PTAX venda'), ('COMPRA', 'PTAX compra')], default='VENDA', max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=12)),
                ('source', models.CharField(default='BCB-OLINDA', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('manually_overridden', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('manually_overridden', False)), fields=('effective_date', 'quote_type'), name='uniq_ptax_effective_quote')],
            },
        ),
    ]
