# Generated by Django 5.1.4 on 2026-08-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Ação'), ('ETF', 'ETF'), ('REIT', 'REIT'), ('BOND', 'Bond'), ('FUND', 'Fundo'), ('OTHER', 'Outro')], max_length=10)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=64)),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('CUSTODY', 'Custódia'), ('MARGIN', 'Margem'), ('OTHER', 'Outro')], default='CASH', max_length=10)),
                ('is_interest_bearing', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
