# Generated by Django 5.1.4 on 2026-08-30 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('APORTE', 'Aporte (entrada de caixa)'), ('WITHDRAWAL', 'Retirada (saída de caixa)'), ('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JUROS', 'Juros/rendimento de caixa'), ('FEE', 'Taxa/corretagem'), ('TAX_WITHHELD', 'Imposto retido nos EUA')], max_length=16)),
                ('trade_date', models.DateField()),
                ('settle_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fee_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('amount_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tax_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('amount_brl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ledger.brokeraccount')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ledger.asset')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_by', to='ledger.financialevent')),
            ],
            options={
                'indexes': [models.Index(fields=['trade_date'], name='ledger_fina_trade_d_80f54b_idx'), models.Index(fields=['event_type'], name='ledger_fina_event_t_152414_idx')],
            },
        ),
    ]
