# Generated by Django 5.1.4 on 2026-08-31 00:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_financialevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(default=datetime.date(2025, 12, 31))),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=24)),
                ('total_cost_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_positions', to='ledger.brokeraccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_positions', to='ledger.asset')),
            ],
        ),
    ]
