# Generated by Django 5.1.4 on 2026-08-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_openingposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='apelido do caixa'),
        ),
    ]
