# Generated by Django 5.1.4 on 2026-09-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_brokeraccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignTaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('foreign_tax_payment_date', models.DateField()),
                ('country_code', models.CharField(max_length=2)),
                ('jurisdiction_level', models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'Estadual'), ('LOCAL', 'Municipal'), ('UNKNOWN', 'Desconhecida')], max_length=16)),
                ('tax_type', models.CharField(choices=[('WITHHOLDING_INCOME_TAX', 'Retenção na fonte (imposto de renda)'), ('INCOME_TAX', 'Imposto de renda'), ('OTHER', 'Outro'), ('UNKNOWN', 'Desconhecido')], max_length=32)),
                ('capture_method', models.CharField(choices=[('IMPORT', 'Importação'), ('MANUAL', 'Manual'), ('SYSTEM', 'Sistema')], max_length=16)),
                ('date_evidence_source', models.CharField(choices=[('BROKER_STATEMENT', 'Extrato da corretora'), ('BROKER_TAX_REPORT', 'Relatório fiscal da corretora'), ('USER_PROVIDED_DOCUMENT', 'Documento fornecido pelo usuário'), ('OTHER_DOCUMENT', 'Outro documento'), ('USER_CONFIRMED', 'Confirmação do usuário'), ('UNKNOWN', 'Desconhecida')], max_length=32)),
                ('source_document_id', models.CharField(blank=True, max_length=128)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_tax_payments', to='ledger.financialevent')),
            ],
        ),
    ]
