# Generated by Django 5.1.4 on 2026-09-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_foreigntaxpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignTaxPaymentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField()),
                ('reason', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='ledger.foreigntaxpayment')),
            ],
        ),
    ]
