# Generated by Django 5.1.4 on 2026-09-07 16:18

from django.db import migrations, models

LEGACY_MAP = {
    "STOCK": "FOREIGN_EQUITY",
    "ETF": "FOREIGN_ETF",
    "BOND": "FOREIGN_BOND",
    "FUND": "FOREIGN_FUND",
    "OTHER": "UNKNOWN",
}
REVERSE_MAP = {v: k for k, v in LEGACY_MAP.items()}


def map_legacy(apps, schema_editor):
    Asset = apps.get_model("ledger", "Asset")
    for old, new in LEGACY_MAP.items():
        Asset.objects.filter(asset_type=old).update(asset_type=new)


def unmap_legacy(apps, schema_editor):
    Asset = apps.get_model("ledger", "Asset")
    for new, old in REVERSE_MAP.items():
        Asset.objects.filter(asset_type=new).update(asset_type=old)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_foreigntaxpaymentaudit'),
    ]

    operations = [
        migrations.RunPython(map_legacy, unmap_legacy),
        migrations.AddField(
            model_name='asset',
            name='is_controlled_entity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='ownership_share_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('FOREIGN_EQUITY', 'Ação estrangeira'), ('FOREIGN_ETF', 'ETF estrangeiro'), ('REIT', 'REIT'), ('US_TREASURY', 'Treasury americano'), ('FOREIGN_BOND', 'Título de dívida estrangeiro'), ('FOREIGN_FUND', 'Fundo estrangeiro'), ('CONTROLLED_ENTITY', 'Entidade controlada (offshore)'), ('TRUST', 'Trust'), ('UNKNOWN', 'Desconhecida')], max_length=32),
        ),
    ]
