# Generated by Django 5.1.4 on 2026-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_asset_is_controlled_entity_asset_ownership_share_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='ownership_share',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='ownership_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('JOINT', 'Conjunta'), ('THIRD_PARTY', 'Terceiros')], default='INDIVIDUAL', max_length=12),
        ),
    ]
