# Generated by Django 5.1.4 on 2026-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_brokeraccount_ownership_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='split_ratio_from',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='split_ratio_to',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='event_type',
            field=models.CharField(choices=[('APORTE', 'Aporte (entrada de caixa)'), ('WITHDRAWAL', 'Retirada (saída de caixa)'), ('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JUROS', 'Juros/rendimento de caixa'), ('FEE', 'Taxa/corretagem'), ('TAX_WITHHELD', 'Imposto retido nos EUA'), ('STOCK_SPLIT', 'Desdobramento (split)'), ('REVERSE_SPLIT', 'Grupamento (reverse split)'), ('CASH_IN_LIEU', 'Fração paga em dinheiro (cash-in-lieu)')], max_length=16),
        ),
    ]
