# Generated by Django 5.1.4 on 2026-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_financialevent_split_ratio_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='transfer_pair_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='event_type',
            field=models.CharField(choices=[('APORTE', 'Aporte (entrada de caixa)'), ('WITHDRAWAL', 'Retirada (saída de caixa)'), ('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JUROS', 'Juros/rendimento de caixa'), ('FEE', 'Taxa/corretagem'), ('TAX_WITHHELD', 'Imposto retido nos EUA'), ('STOCK_SPLIT', 'Desdobramento (split)'), ('REVERSE_SPLIT', 'Grupamento (reverse split)'), ('CASH_IN_LIEU', 'Fração paga em dinheiro (cash-in-lieu)'), ('BROKER_TRANSFER_IN', 'Transferência de custódia (entrada)'), ('BROKER_TRANSFER_OUT', 'Transferência de custódia (saída)')], max_length=32),
        ),
    ]
