# Generated by Django 5.1.4 on 2026-09-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_financialevent_transfer_pair_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='ledger.financialevent'),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='event_type',
            field=models.CharField(choices=[('APORTE', 'Aporte (entrada de caixa)'), ('WITHDRAWAL', 'Retirada (saída de caixa)'), ('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JUROS', 'Juros/rendimento de caixa'), ('FEE', 'Taxa/corretagem'), ('TAX_WITHHELD', 'Imposto retido nos EUA'), ('STOCK_SPLIT', 'Desdobramento (split)'), ('REVERSE_SPLIT', 'Grupamento (reverse split)'), ('CASH_IN_LIEU', 'Fração paga em dinheiro (cash-in-lieu)'), ('BROKER_TRANSFER_IN', 'Transferência de custódia (entrada)'), ('BROKER_TRANSFER_OUT', 'Transferência de custódia (saída)'), ('WITHHOLDING_REFUND', 'Restituição de imposto retido no exterior')], max_length=32),
        ),
    ]
