# Generated by Django 5.1.4 on 2026-09-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_financialevent_refund_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='SCHWAB', max_length=32)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='ledger.brokeraccount')),
            ],
        ),
    ]
