# Generated by Django 5.1.4 on 2026-08-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField()),
                ('rule_version', models.CharField(max_length=64)),
                ('brackets', models.JSONField()),
                ('foreign_tax_credit_enabled', models.BooleanField(default=True)),
                ('loss_carryforward_enabled', models.BooleanField(default=True)),
                ('fx_cash_policy', models.JSONField(default=dict)),
                ('quote_type', models.CharField(default='VENDA', max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tax_year', 'rule_version'), name='uniq_taxrule_year_version')],
            },
        ),
    ]
