# Generated by Django 5.1.4 on 2026-08-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
