# Generated by Django 5.1.4 on 2026-08-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_taxrule_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('rule_version', models.CharField(max_length=64)),
                ('income_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('loss_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('taxable_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tax_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('withholding_credit_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tax_due_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('loss_carryforward_brl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('detail', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
