# Generated by Django 5.1.4 on 2026-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='date_rule',
            field=models.CharField(choices=[('ACQUISITION_DATE', 'Data da aquisição'), ('DISPOSAL_DATE', 'Data da alienação'), ('INCOME_RECEIPT_DATE', 'Data do recebimento do rendimento'), ('FOREIGN_TAX_PAYMENT_DATE', 'Data do pagamento do imposto no exterior'), ('REFERENCE_DATE', 'Data de referência informada')], default='INCOME_RECEIPT_DATE', max_length=32),
        ),
    ]
