# Generated by Django 5.1.4 on 2026-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_taxrule_date_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_dsdp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='residency_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residency_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_residency_status',
            field=models.CharField(choices=[('BRAZIL_RESIDENT', 'Residente fiscal pleno no Brasil'), ('NON_RESIDENT', 'Não residente'), ('PART_YEAR_RESIDENT', 'Residente por parte do ano-calendário'), ('UNKNOWN', 'Desconhecida')], default='UNKNOWN', max_length=20),
        ),
    ]
