# Generated by Django 5.1.4 on 2026-09-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_profile_has_dsdp_profile_residency_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='external_assets_declared_complete',
            field=models.BooleanField(default=False),
        ),
    ]
