# Generated by Django 5.1.4 on 2026-09-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_profile_external_assets_declared_complete'),
        ('ledger', '0010_financialevent_transfer_pair_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_year', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount_brl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remaining_brl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loss_records', to='ledger.financialevent')),
            ],
        ),
        migrations.CreateModel(
            name='LossCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount_brl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='fiscal.lossrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'year'), name='uniq_loss_comp_year')],
            },
        ),
    ]
