# Generated by Django 5.1.4 on 2026-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_lossrecord_losscompensation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirpfSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_year', models.PositiveIntegerField(unique=True)),
                ('schema_version', models.CharField(max_length=64)),
                ('groups', models.JSONField(default=dict)),
                ('countries', models.JSONField(default=dict)),
                ('is_homologated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
