# Generated by Django 5.1.4 on 2026-08-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_version', models.PositiveIntegerField(default=1)),
                ('argon2_salt', models.BinaryField()),
                ('argon2_memory_cost', models.PositiveIntegerField(default=65536)),
                ('argon2_iterations', models.PositiveIntegerField(default=3)),
                ('argon2_parallelism', models.PositiveIntegerField(default=4)),
                ('wrapped_vault_key_password', models.BinaryField(blank=True, null=True)),
                ('wrapped_vault_key_recovery', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
