# Generated by Django 5.1.4 on 2026-08-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=64)),
                ('resource_type', models.CharField(blank=True, default='', max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='OK', max_length=32)),
                ('metadata_safe', models.JSONField(default=dict)),
                ('event_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
