# Generated by Django 5.1.4 on 2026-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_securityauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_filename', models.BinaryField()),
                ('wrapped_file_key', models.BinaryField()),
                ('file_path', models.CharField(max_length=512)),
                ('file_hash', models.CharField(max_length=64)),
                ('crypto_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
